import { useMemo, useState } from 'react'
import { Clipboard, FileSearch, ShieldCheck } from 'lucide-react'
import { analyzeCsp, assessEvidence } from '../lib/diagnostic'

const types = ['접근 제어', '입력 처리', 'XSS 출력 맥락', 'SSRF·리다이렉트', '보안 헤더·CSP', '인증·세션']
export function DiagnosticWorkbench() {
  const [type, setType] = useState(types[0]); const [scope, setScope] = useState(''); const [baseline, setBaseline] = useState(''); const [variation, setVariation] = useState(''); const [serverEvidence, setServerEvidence] = useState(''); const [csp, setCsp] = useState('')
  const evidence = useMemo(() => assessEvidence({ baseline, variation, serverEvidence }), [baseline, variation, serverEvidence])
  const cspResult = useMemo(() => csp.trim() ? analyzeCsp(csp) : null, [csp])
  const report = `# 진단 기록\n\n- 유형: ${type}\n- 승인 범위: ${scope || '미기록'}\n- 증거 수준: ${evidence.status}\n\n## 기준 응답\n${baseline || '미기록'}\n\n## 변형 응답\n${variation || '미기록'}\n\n## 서버 측 증거\n${serverEvidence || '미기록'}\n\n## 다음 검증\n${evidence.nextStep}`
  return <section className="diag-workbench"><header><div><p className="eyebrow">EVIDENCE FIRST DIAGNOSTICS</p><h1>진단 워크벤치</h1><p>허가된 환경에서 관측값을 기록하고, 단일 반응이 아닌 증거 연결로 판정합니다.</p></div><ShieldCheck size={28}/></header><div className="diag-grid"><div className="diag-panel"><h2>1. 범위와 관측 기록</h2><label>진단 유형<select value={type} onChange={event => setType(event.target.value)}>{types.map(value => <option key={value}>{value}</option>)}</select></label><label>승인 범위·대상<textarea value={scope} onChange={event => setScope(event.target.value)} placeholder="예: 사내 스테이징, 계정 A·B, 2026-09-12 승인"/></label><label>기준 요청·응답<textarea value={baseline} onChange={event => setBaseline(event.target.value)} placeholder="인증 상태, 요청 ID, 상태 코드, 본문 또는 화면 변화"/></label><label>변형 후 관측<textarea value={variation} onChange={event => setVariation(event.target.value)} placeholder="한 번에 하나의 조건만 바꾼 뒤 달라진 결과"/></label><label>서버 측 증거<textarea value={serverEvidence} onChange={event => setServerEvidence(event.target.value)} placeholder="요청 ID, 감사 로그, 상태 변경, 코드 위치. 없으면 비워두세요."/></label></div><aside className="diag-panel diag-assessment"><h2>2. 증거 수준</h2><span className={`diag-status ${evidence.status}`}>{evidence.status === 'CONFIRMED' ? '확인됨' : evidence.status === 'NEEDS_EVIDENCE' ? '추가 증거 필요' : evidence.status === 'NO_SIGNAL' ? '신호 부족' : '미시작'}</span><p>{evidence.summary}</p><h3>다음 단계</h3><p>{evidence.nextStep}</p><button onClick={() => navigator.clipboard.writeText(report)}><Clipboard size={15}/> 기록 복사</button><pre>{report}</pre></aside></div><section className="diag-panel csp-workbench"><div><h2>3. CSP 헤더 분석</h2><p>헤더 값만 분석한다. 실제 취약성 판정에는 애플리케이션의 출력 맥락과 적용 응답 확인이 추가로 필요하다.</p></div><textarea value={csp} onChange={event => setCsp(event.target.value)} placeholder="Content-Security-Policy 헤더 값을 붙여넣으세요"/>{cspResult && <div className="csp-results"><p>Directive {Object.keys(cspResult.directives).length}개 · 지적 {cspResult.findings.length}건</p>{cspResult.findings.map(finding => <article key={finding.code}><b className={finding.severity}>{finding.severity}</b><div><strong>{finding.title}</strong><span>{finding.detail}</span><small>조치: {finding.remediation}</small></div></article>)}{cspResult.findings.length === 0 && <p>현재 규칙으로 지적된 항목이 없다. 실제 응답 헤더와 적용 경로를 별도 확인하세요.</p>}</div>}</section></section>
}
