import { useEffect, useMemo, useState } from 'react'
import { BookOpen, Brain, History, Play, Save, Send, X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

type Assessment={skillCode:string;score:number;confidence:string;rationale:string;nextAction:string;evidenceCount:number;evaluationCount:number;assessedAt:string}
type Case={id:string;slug:string;title:string;caseType:string;skillCode:string;difficulty:number;promptMd:string}
type Attempt={id:string;trainingCase:Case;status:string;answerMd:string;feedbackMd:string|null;score:number|null;startedAt:string;submittedAt:string|null}
type Dashboard={assessments:Assessment[];recommendations:Case[]}
type AnswerFields={verdict:string;evidence:string;conditions:string;impact:string;rootCause:string;remediation:string;verification:string}
class ApiError extends Error { constructor(public status:number,message:string){super(message)} }

const labels:Record<string,string>={REPORTING:'보고·설계',REQUIREMENTS:'요구사항',JAVA_SPRING:'Java·Spring',SQL_DML:'SQL',DATA_QUALITY:'데이터 품질',DOCKER_DEPLOY:'Docker·배포',API_SECURITY:'웹·API 보안',AUTHENTICATION:'인증',AUTHORIZATION:'인가·권한',SESSION_COOKIE:'세션·쿠키',XSS_CONTEXT:'XSS 출력 맥락',FILE_UPLOAD:'파일 업로드',SSRF:'SSRF',NETWORK_TLS:'네트워크·TLS',SECRETS_MANAGEMENT:'비밀값 관리'}
const api=(path:string,init?:RequestInit)=>fetch(`/api/training${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})},...init}).then(async r=>{if(!r.ok){const body=await r.json().catch(()=>({message:''}));throw new ApiError(r.status,body.message||`서버 응답 ${r.status}`)}return r.json()})
const emptyAnswer=():AnswerFields=>({verdict:'',evidence:'',conditions:'',impact:'',rootCause:'',remediation:'',verification:''})
const toMarkdown=(a:AnswerFields)=>`## 판정\n${a.verdict}\n\n## 근거\n${a.evidence}\n\n## 성립 조건\n${a.conditions}\n\n## 영향 범위\n${a.impact}\n\n## 원인\n${a.rootCause}\n\n## 조치\n${a.remediation}\n\n## 재검증\n${a.verification}`

export function CompetencyPage(){
  const [data,setData]=useState<Dashboard|null>(null); const [cases,setCases]=useState<Case[]>([]); const [history,setHistory]=useState<Attempt[]>([])
  const [selected,setSelected]=useState<Assessment|null>(null); const [active,setActive]=useState<Attempt|null>(null); const [answer,setAnswer]=useState<AnswerFields>(emptyAnswer); const [tab,setTab]=useState<'overview'|'cases'|'history'>('overview'); const [error,setError]=useState(''); const [submitting,setSubmitting]=useState(false)
  const load=async()=>{for(let retry=0;retry<3;retry++){try{const [d,c,h]=await Promise.all([api('/dashboard'),api('/cases'),api('/attempts')]);setData(d);setCases(c);setHistory(h);setError('');return}catch(e){if(e instanceof ApiError&&e.status===502&&retry<2){await new Promise(resolve=>setTimeout(resolve,1000));continue}setError(e instanceof Error?e.message:'불러오기 실패');return}}}
  useEffect(()=>{void load()},[])
  const weakest=useMemo(()=>data?.assessments.slice().sort((a,b)=>a.score-b.score)[0]??null,[data])
  const previous=useMemo(()=>active?history.find(item=>item.trainingCase.id===active.trainingCase.id&&item.id!==active.id&&item.status==='SUBMITTED')??null:null,[active,history])
  const start=async(c:Case)=>{try{const a:Attempt=await api(`/cases/${c.id}/attempts`,{method:'POST'});setActive(a);setAnswer(emptyAnswer());setTab('cases')}catch(e){setError(e instanceof Error?e.message:'시작 실패')}}
  const save=async(submit=false)=>{if(!active||submitting)return;setSubmitting(submit);try{const a:Attempt=await api(`/attempts/${active.id}/${submit?'submit':'answer'}`,{method:submit?'POST':'PUT',body:JSON.stringify({answer:toMarkdown(answer)})});setActive(a);await load()}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setSubmitting(false)}}
  const evaluateExisting=async()=>{if(!active||submitting)return;setSubmitting(true);try{const a:Attempt=await api(`/attempts/${active.id}/evaluate`,{method:'POST'});setActive(a);await load()}catch(e){setError(e instanceof Error?e.message:'AI 채점 실패')}finally{setSubmitting(false)}}
  return <div className="page competency-page">
    <section className="competency-hero"><div><p className="eyebrow">PERSONAL TRAINING SYSTEM</p><h1>역량 강화</h1><p>점수보다 근거와 재검증을 우선합니다. 과거 답안은 보존되고, 재시도는 별도 기록으로 남습니다.</p></div><div className="competency-next"><small>현재 우선 보완</small><strong>{weakest?labels[weakest.skillCode]??weakest.skillCode:'평가 준비 중'}</strong><span>{weakest?`${weakest.score}점 · AI 평가 ${weakest.evaluationCount}회`:''}</span></div></section>
    <nav className="competency-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Brain size={16}/>역량</button><button className={tab==='cases'?'active':''} onClick={()=>setTab('cases')}><BookOpen size={16}/>문제 보관함</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={16}/>과거 기록</button></nav>
    {error&&<p className="competency-error">{error}</p>}
    {tab==='overview'&&<><section className="competency-grid">{data?.assessments.map(a=><button className="competency-card" key={a.skillCode} onClick={()=>setSelected(a)} title={`${a.rationale} · 클릭하여 상세 보기`}><span>{labels[a.skillCode]??a.skillCode}</span><strong>{a.score.toFixed(0)}</strong><small>{a.confidence==='HIGH'?'신뢰도 높음':a.confidence==='MEDIUM'?'신뢰도 중간':'신뢰도 낮음'} · AI 평가 {a.evaluationCount}회</small><em>{a.rationale}</em></button>)}</section><section className="competency-recommend"><h2>다음 추천 과제</h2>{data?.recommendations.map(c=><article key={c.id}><div><b>{c.title}</b><span>{labels[c.skillCode]??c.skillCode} · 난이도 {c.difficulty}</span></div><button onClick={()=>void start(c)}><Play size={15}/> 시작</button></article>)}</section></>}
    {tab==='cases'&&<section className="case-list"><h2>문제 보관함</h2><p>정적 진단과 보고서 리뷰부터 시작합니다. 실습형 케이스는 격리 환경 검증 후 추가됩니다.</p>{cases.map(c=><article key={c.id}><div><small>{c.caseType==='REPORT_REVIEW'?'보고서 리뷰':'정적 진단'} · {labels[c.skillCode]??c.skillCode} · 난이도 {c.difficulty}</small><h3>{c.title}</h3><p>{c.promptMd.split('\n').filter(Boolean).slice(1,3).join(' ')}</p></div><button onClick={()=>void start(c)}><Play size={15}/> 풀기</button></article>)}</section>}
    {tab==='history'&&<section className="case-list"><h2>과거 기록</h2>{history.length===0?<p>아직 제출한 답안이 없습니다.</p>:history.map(a=><article key={a.id}><div><small>{new Date(a.startedAt).toLocaleString('ko-KR')} · {a.status}</small><h3>{a.trainingCase.title}</h3><p>{a.score===null?'작성 중':'점수 '+a.score.toFixed(0)+'점'}</p></div><button onClick={()=>{setActive(a);setAnswer(emptyAnswer());setTab('cases')}}>열기</button></article>)}</section>}
    {selected&&<div className="competency-modal-backdrop" onMouseDown={()=>setSelected(null)}><aside className="competency-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">SKILL DETAIL</p><h2>{labels[selected.skillCode]??selected.skillCode}</h2><strong className="modal-score">{selected.score.toFixed(0)}점</strong><p>{selected.confidence} · AI 평가 {selected.evaluationCount}회 · 초기 근거 {selected.evidenceCount}건</p><h3>종합 피드백</h3><p>{selected.rationale}</p><h3>다음 행동</h3><p>{selected.nextAction}</p></aside></div>}
    {active&&<div className="competency-modal-backdrop" onMouseDown={()=>!submitting&&setActive(null)}><aside className="competency-workspace" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setActive(null)} disabled={submitting}><X/></button><p className="eyebrow">{active.trainingCase.caseType} · {labels[active.trainingCase.skillCode]??active.trainingCase.skillCode}</p><h2>{active.trainingCase.title}</h2><div className="case-prompt"><ReactMarkdown>{active.trainingCase.promptMd}</ReactMarkdown></div>{previous&&<details className="case-previous"><summary>이전 제출 답안 보기 · {previous.score?.toFixed(0)}점</summary><ReactMarkdown>{previous.answerMd}</ReactMarkdown></details>}<section className="answer-fields">{([['verdict','1. 판정','취약 / 정상 / 추가 증거 필요 중 하나와 짧은 결론'],['evidence','2. 근거','코드 위치, 요청·응답, 로그, 설정값'],['conditions','3. 성립 조건','인증 상태, 역할, 입력값, 배포 조건'],['impact','4. 영향 범위','가능한 영향과 제한 조건'],['rootCause','5. 원인','신뢰 경계와 데이터 흐름'],['remediation','6. 조치','코드·서버 설정·운영 계층별 조치'],['verification','7. 재검증','정상·악성·경계 조건 테스트 계획']] as [keyof AnswerFields,string,string][]).map(([key,title,placeholder])=><label key={key}>{title}<textarea value={answer[key]} onChange={e=>setAnswer({...answer,[key]:e.target.value})} placeholder={placeholder} disabled={active.status==='SUBMITTED'||submitting}/></label>)}</section>{active.feedbackMd&&<div className="case-feedback"><ReactMarkdown>{active.feedbackMd}</ReactMarkdown></div>}<footer>{active.status==='SUBMITTED'?<><span>제출 완료 · 새 시도를 시작하면 이전 답안과 현재 답안을 비교할 수 있습니다.</span>{!active.feedbackMd?.includes('## AI 판정')&&<button className="primary" onClick={()=>void evaluateExisting()} disabled={submitting}><Send size={15}/>{submitting?' AI 채점 중…':' AI로 다시 평가'}</button>}</>:<><button onClick={()=>void save(false)} disabled={submitting}><Save size={15}/> 임시 저장</button><button className="primary" onClick={()=>void save(true)} disabled={submitting}><Send size={15}/>{submitting?' AI 채점 중…':' 제출·AI 피드백 받기'}</button></>}</footer></aside></div>}
  </div>
}
