import { useEffect, useMemo, useRef, useState, type KeyboardEvent } from 'react'
import { Brain, History, Send, ShieldQuestion, X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import '../styles/blackbox-training.css'
import { captureClosedSession } from './CompetencyPage.logic'

type Assessment={skillCode:string;score:number;rationale:string;nextAction:string;evaluationCount:number;blackBoxScore:number|null;blackBoxEvaluationCount:number;blackBoxRationale:string|null;blackBoxNextAction:string|null}
type Message={role:'USER'|'SIMULATOR'|'COACH';text:string}
type Session={id:string;title:string;intro:string;skillCode:string;status:'ACTIVE'|'CLOSED';messages:string[];feedbackMd:string|null;score:number|null;startedAt:string;closedAt:string|null}
const labels:Record<string,string>={API_SECURITY:'웹·API 보안',AUTHENTICATION:'인증',AUTHORIZATION:'인가·권한',BUSINESS_LOGIC:'업무 규칙·동시성',SESSION_COOKIE:'세션·토큰 안전성',CLIENT_STATE_TRUST:'쿠키·웹 스토리지 신뢰',XSS_CONTEXT:'XSS 출력 맥락',CSRF:'CSRF',INPUT_INTEGRITY:'입력 무결성·파라미터 조작',URL_REDIRECT:'리다이렉트·외부 URL',FILE_UPLOAD:'파일 업로드',FILE_DOWNLOAD:'파일 다운로드·경로 검증',SQLI_QUERY:'SQL 데이터 흐름',SSRF:'SSRF·File Inclusion',ERROR_HANDLING:'오류 처리·정보 노출',WEB_HARDENING:'웹 노출면·보안 설정',NETWORK_TLS:'네트워크·TLS',SECRETS_MANAGEMENT:'비밀값 관리',LINUX_HARDENING:'Linux 하드닝',CLOUD_IAM:'클라우드 IAM',CLOUD_NETWORK:'클라우드 네트워크',CLOUD_DATA_SECURITY:'클라우드 데이터 보안',CONTAINER_SECURITY:'컨테이너 보안',NETWORK_ACCESS_CONTROL:'네트워크 접근통제',NETWORK_DEFENSE:'WAF·IDS·IPS',SECURITY_MONITORING:'보안 모니터링'}
const securitySkillCodes=new Set(Object.keys(labels))
const messages=(values:string[]):Message[]=>values.map(value=>value.startsWith('USER::')?{role:'USER',text:value.slice(6)}:value.startsWith('SIMULATOR::')?{role:'SIMULATOR',text:value.slice(11)}:{role:'COACH',text:value.replace(/^COACH::/,'')})
async function api<T>(path:string,init?:RequestInit):Promise<T>{
 const response=await fetch(`/api/training${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers??{})},...init})
 const raw=await response.text()
 let body:unknown=null
 if(raw.trim()){try{body=JSON.parse(raw)}catch{throw new Error(response.ok?'서버가 읽을 수 없는 응답을 반환했습니다.':`서버 응답 ${response.status}`)}}
 if(!response.ok){const message=typeof body==='object'&&body!==null&&'message' in body?String((body as {message?:unknown}).message??''):'';throw new Error(message||`서버 응답 ${response.status}`)}
 if(!raw.trim())throw new Error('서버가 빈 응답을 반환했습니다.')
 return body as T
}

export function CompetencyPage(){
 const HISTORY_PAGE_SIZE=20
 const [dashboard,setDashboard]=useState<{assessments:Assessment[]}|null>(null),[history,setHistory]=useState<Session[]>([]),[active,setActive]=useState<Session|null>(null)
 const [tab,setTab]=useState<'overview'|'scenarios'|'history'>('overview'),[archive,setArchive]=useState<Session|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[completion,setCompletion]=useState(false)
 const [historyPage,setHistoryPage]=useState(0),[hasMoreHistory,setHasMoreHistory]=useState(false),[historyBusy,setHistoryBusy]=useState(false)
 // #11 -- the completion modal reads this, never `active` directly: load()'s background reload legitimately
 // sets `active` to null once the just-closed session no longer shows up as ACTIVE, which used to make the
 // modal vanish out from under the learner right after it appeared.
 const [closedSession,setClosedSession]=useState<Session|null>(null)
 const threadRef=useRef<HTMLDivElement>(null),[followThread,setFollowThread]=useState(true)
 // #15 -- /black-box/sessions is now paginated server-side (a learner with a long history no longer force-
 // loads every past session on every visit); this page still only ever shows CLOSED ones, so a fetched
 // page can come back short even when more history exists (the lone ACTIVE session, if any, got filtered
 // out) -- treating "got a full page back" as the "there might be more" signal is an acceptable
 // approximation given at most one session is ever ACTIVE at a time.
 const load=async()=>{try{const [d,current,h]=await Promise.all([api<{assessments:Assessment[]}>('/dashboard'),api<{session:Session|null}>('/black-box/active-session'),api<Session[]>(`/black-box/sessions?page=0&size=${HISTORY_PAGE_SIZE}`)]);setDashboard(d);setActive(current.session);setHistory(h.filter(item=>item.status==='CLOSED'));setHistoryPage(0);setHasMoreHistory(h.length>=HISTORY_PAGE_SIZE);setError('');if(current.session?.status==='CLOSED')setCompletion(true)}catch(e){setError(e instanceof Error?e.message:'불러오기 실패')}}
 const loadMoreHistory=async()=>{if(historyBusy)return;setHistoryBusy(true);try{const nextPage=historyPage+1;const h=await api<Session[]>(`/black-box/sessions?page=${nextPage}&size=${HISTORY_PAGE_SIZE}`);setHistory(prev=>[...prev,...h.filter(item=>item.status==='CLOSED')]);setHistoryPage(nextPage);setHasMoreHistory(h.length>=HISTORY_PAGE_SIZE)}catch(e){setError(e instanceof Error?e.message:'과거 기록을 더 불러오지 못했습니다.')}finally{setHistoryBusy(false)}}
 useEffect(()=>{void load()},[])
 useEffect(()=>{if(followThread&&threadRef.current)threadRef.current.scrollTop=threadRef.current.scrollHeight},[active?.messages.length,followThread])
 const weakest=useMemo(()=>dashboard?.assessments.filter(item=>item.blackBoxScore!==null).sort((a,b)=>(a.blackBoxScore??100)-(b.blackBoxScore??100))[0]??null,[dashboard])
 const start=async(skillCode?:string)=>{setBusy(true);try{const next=await api<Session>('/black-box/sessions',{method:'POST',body:JSON.stringify({skillCode})});setActive(next);setFollowThread(true);setMessage('');setCompletion(false);setTab('scenarios')}catch(e){setError(e instanceof Error?e.message:'새 사건을 시작하지 못했습니다.')}finally{setBusy(false)}}
 const send=async()=>{if(!active||active.status!=='ACTIVE'||!message.trim()||busy)return;setBusy(true);try{const next=await api<Session>(`/black-box/sessions/${active.id}/messages`,{method:'POST',body:JSON.stringify({message})});setActive(next);setMessage('');setClosedSession(prev=>captureClosedSession(next,prev));if(next.status==='CLOSED'){setCompletion(true);void load()}}catch(e){setError(e instanceof Error?e.message:'메시지를 전송하지 못했습니다.')}finally{setBusy(false)}}
 const onKeyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();void send()}}
 return <div className="page blackbox-page">
  <section className="blackbox-hero"><div><p className="blackbox-eyebrow">PERSONAL TRAINING SYSTEM</p><h1>역량 강화</h1><p>사건 하나를 대화로 풀고, 종료된 세션 전체를 근거로 역량을 다시 평가합니다.</p></div><div className="blackbox-hero-metric"><small>현재 우선 보완</small><strong>{weakest?labels[weakest.skillCode]??weakest.skillCode:'평가 준비 중'}</strong><span>{weakest?`${weakest.blackBoxScore?.toFixed(0)}점 · 사건 ${weakest.blackBoxEvaluationCount}회`:'종료된 사건이 없습니다.'}</span></div></section>
  <nav className="blackbox-tabs"><button aria-pressed={tab==='overview'} onClick={()=>setTab('overview')}><Brain size={16}/>종합 역량</button><button aria-pressed={tab==='scenarios'} onClick={()=>setTab('scenarios')}><ShieldQuestion size={16}/>블랙박스 사건</button><button aria-pressed={tab==='history'} onClick={()=>setTab('history')}><History size={16}/>과거 기록</button></nav>
  {error&&<p className="blackbox-alert">{error}</p>}
  {tab==='overview'&&<section className="blackbox-score-grid">{dashboard?.assessments.map(item=><article className="blackbox-score-card" key={item.skillCode}><span>{labels[item.skillCode]??item.skillCode}</span><div className="blackbox-score-pair"><div><small>기초 판단</small><strong>{item.score.toFixed(0)}</strong><em>기존 평가 {item.evaluationCount}회</em></div><div><small>블랙박스 추리</small><strong>{item.blackBoxScore===null?'—':item.blackBoxScore.toFixed(0)}</strong><em>{item.blackBoxEvaluationCount===0?'측정 전':`사건 ${item.blackBoxEvaluationCount}회`}</em></div></div><p>{item.blackBoxRationale??item.rationale}</p><small>{item.blackBoxNextAction??item.nextAction}</small></article>)}</section>}
  {tab==='scenarios'&&<section className="blackbox-chat-shell">{!active?<div className="blackbox-empty-chat"><h2>훈련할 보안 역량을 직접 선택하세요.</h2><p>선택 전에는 사건이 정해지지 않습니다. 선택하면 AI가 현재 평가를 읽고 새 현업형 사건을 만들어 대화를 시작합니다.</p><div className="blackbox-topic-grid">{dashboard?.assessments.filter(item=>securitySkillCodes.has(item.skillCode)).map(item=><button key={item.skillCode} className="blackbox-topic" onClick={()=>void start(item.skillCode)} disabled={busy}><strong>{labels[item.skillCode]}</strong><span>{item.blackBoxScore===null?'첫 사건 시작':`현재 ${item.blackBoxScore.toFixed(0)}점`}</span></button>)}</div></div>:<><header className="blackbox-chat-header"><div><p className="blackbox-eyebrow">BLACK-BOX SESSION · {labels[active.skillCode]??active.skillCode}</p><h2>{active.title}</h2></div><span className={`blackbox-session-state ${active.status==='CLOSED'?'closed':''}`}>{active.status==='ACTIVE'?'진행 중':'종료됨'}</span></header><div className="blackbox-thread" ref={threadRef} onScroll={e=>{const node=e.currentTarget;setFollowThread(node.scrollHeight-node.scrollTop-node.clientHeight<28)}}>{messages(active.messages).map((item,index)=><article className={`blackbox-message ${item.role==='USER'?'user':item.role==='SIMULATOR'?'target':'coach'}`} key={`${index}-${item.text}`}><b>{item.role==='USER'?'나':item.role==='SIMULATOR'?'가상 대상':'AI 진단 파트너'}</b><ReactMarkdown>{item.text}</ReactMarkdown></article>)}</div>{active.status==='ACTIVE'?<div className="blackbox-composer"><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={onKeyDown} placeholder="질문하거나 시도할 행동을 자연스럽게 적으세요." maxLength={1800}/><button className="blackbox-primary" onClick={()=>void send()} disabled={busy||!message.trim()}><Send size={16}/>{busy?'전송 중…':'보내기'}</button></div>:<div className="blackbox-closed-bar">이 사건은 종료되었습니다. 새 세션을 시작하면 다른 사건으로 이어집니다.<button className="blackbox-primary" onClick={()=>{setActive(null);setCompletion(false)}} disabled={busy}>주제 선택</button></div>}</>}</section>}
  {tab==='history'&&<section className="blackbox-history-list">{history.length===0?<p className="blackbox-empty">종료된 사건이 없습니다.</p>:<>{history.map(item=><article className="blackbox-history-card" key={item.id}><div><small>{new Date(item.closedAt??item.startedAt).toLocaleString('ko-KR')} · {labels[item.skillCode]??item.skillCode}</small><h2>{item.title}</h2><p>{item.score===null?'평가 준비 중':`${item.score.toFixed(0)}점 · ${item.feedbackMd?.replace(/[#*\n]/g,' ').slice(0,90)??'대화 기록'}`}</p></div><button className="blackbox-history-open" onClick={()=>setArchive(item)}>대화 보기</button></article>)}{hasMoreHistory&&<button className="blackbox-history-load-more" onClick={()=>void loadMoreHistory()} disabled={historyBusy}>{historyBusy?'불러오는 중…':'더 보기'}</button>}</>}</section>}
  {completion&&closedSession&&<div className="blackbox-overlay"><section className="blackbox-completion" role="dialog" aria-modal="true"><h2>이번 사건이 종료되었습니다.</h2><p>대화 전체를 근거로 종합 역량에 반영했습니다. 과거 기록에서 당시 대화를 다시 볼 수 있습니다.</p><div><button onClick={()=>{setCompletion(false);setTab('history')}}>과거 기록 보기</button><button className="blackbox-primary" onClick={()=>{setActive(null);setCompletion(false);setClosedSession(null)}} disabled={busy}>주제 선택</button></div></section></div>}
  {archive&&<div className="blackbox-overlay" onMouseDown={()=>setArchive(null)}><aside className="blackbox-archive" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="blackbox-icon-button" aria-label="닫기" onClick={()=>setArchive(null)}><X/></button><p className="blackbox-eyebrow">PAST SESSION · READ ONLY</p><h2>{archive.title}</h2><small>{new Date(archive.closedAt??archive.startedAt).toLocaleString('ko-KR')}</small><div className="blackbox-archive-thread">{messages(archive.messages).map((item,index)=><article className={`blackbox-message ${item.role==='USER'?'user':item.role==='SIMULATOR'?'target':'coach'}`} key={`${index}-${item.text}`}><b>{item.role==='USER'?'나':item.role==='SIMULATOR'?'가상 대상':'진단 안내'}</b><ReactMarkdown>{item.text}</ReactMarkdown></article>)}</div>{archive.feedbackMd&&<section className="blackbox-archive-feedback"><ReactMarkdown>{archive.feedbackMd}</ReactMarkdown></section>}</aside></div>}
 </div>
}
