import { useEffect, useMemo, useState } from 'react'
import { Brain, ClipboardCheck, History, MessageCircle, Save, Send, ShieldQuestion, X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import '../styles/blackbox-training.css'

type Assessment={skillCode:string;score:number;rationale:string;nextAction:string;evaluationCount:number;blackBoxScore:number|null;blackBoxEvaluationCount:number;blackBoxRationale:string|null;blackBoxNextAction:string|null}
type Scenario={slug:string;title:string;intro:string;skillCode:string;difficulty:number}
type Message={role:'USER'|'COACH';text:string}
type Session={id:string;title:string;intro:string;skillCode:string;status:'ACTIVE'|'CLOSED';messages:string[];facts:string;hypotheses:string;unknowns:string;finalReport:string|null;feedbackMd:string|null;startedAt:string}
type Notes={facts:string;hypotheses:string;unknowns:string}
const labels:Record<string,string>={API_SECURITY:'웹·API 보안',AUTHENTICATION:'인증',AUTHORIZATION:'인가·권한',SESSION_COOKIE:'세션·쿠키',XSS_CONTEXT:'XSS 출력 맥락',FILE_UPLOAD:'파일 업로드',SQLI_QUERY:'SQL 데이터 흐름',SSRF:'SSRF',NETWORK_TLS:'네트워크·TLS',SECRETS_MANAGEMENT:'비밀값 관리'}
const emptyNotes=():Notes=>({facts:'',hypotheses:'',unknowns:''})
const messages=(values:string[]):Message[]=>values.map(value=>value.startsWith('USER::')?{role:'USER',text:value.slice(6)}:{role:'COACH',text:value.replace(/^COACH::/,'')})
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/training${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers??{})},...init});if(!response.ok){const body=await response.json().catch(()=>({message:''})) as {message?:string};throw new Error(body.message||`서버 응답 ${response.status}`)}return response.json() as Promise<T>}

export function CompetencyPage(){
 const [dashboard,setDashboard]=useState<{assessments:Assessment[]}|null>(null),[scenarios,setScenarios]=useState<Scenario[]>([]),[history,setHistory]=useState<Session[]>([])
 const [tab,setTab]=useState<'overview'|'scenarios'|'history'>('overview'),[active,setActive]=useState<Session|null>(null),[archive,setArchive]=useState<Session|null>(null)
 const [notes,setNotes]=useState<Notes>(emptyNotes()),[message,setMessage]=useState(''),[closing,setClosing]=useState(false),[verdict,setVerdict]=useState('추가 증거 필요'),[conclusion,setConclusion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=async()=>{try{const [d,s,h]=await Promise.all([api<{assessments:Assessment[]}>('/dashboard'),api<Scenario[]>('/black-box/scenarios'),api<Session[]>('/black-box/sessions')]);setDashboard(d);setScenarios(s);setHistory(h);setError('')}catch(e){setError(e instanceof Error?e.message:'불러오기 실패')}}
 useEffect(()=>{void load()},[])
 const weakest=useMemo(()=>dashboard?.assessments.filter(item=>item.blackBoxScore!==null).sort((a,b)=>(a.blackBoxScore??100)-(b.blackBoxScore??100))[0]??null,[dashboard])
 const begin=async(scenario:Scenario)=>{setBusy(true);try{const session=await api<Session>(`/black-box/scenarios/${scenario.slug}/sessions`,{method:'POST'});setActive(session);setNotes(emptyNotes());setMessage('');setClosing(false);setConclusion('');setNotice('새 사건을 시작했습니다. 이전 사건의 대화와 메모는 이 세션에 포함되지 않습니다.')}catch(e){setError(e instanceof Error?e.message:'사건 시작 실패')}finally{setBusy(false)}}
 const send=async()=>{if(!active||!message.trim()||busy)return;setBusy(true);try{setActive(await api<Session>(`/black-box/sessions/${active.id}/messages`,{method:'POST',body:JSON.stringify({message})}));setMessage('')}catch(e){setError(e instanceof Error?e.message:'대화 전송 실패')}finally{setBusy(false)}}
 const saveNotes=async()=>{if(!active||busy)return;setBusy(true);try{setActive(await api<Session>(`/black-box/sessions/${active.id}/notes`,{method:'PUT',body:JSON.stringify(notes)}));setNotice('조사 메모를 저장했습니다.')}catch(e){setError(e instanceof Error?e.message:'메모 저장 실패')}finally{setBusy(false)}}
 const finish=async()=>{if(!active||!conclusion.trim()||busy)return;setBusy(true);try{setActive(await api<Session>(`/black-box/sessions/${active.id}/close`,{method:'POST',body:JSON.stringify({verdict,conclusion})}));setClosing(false);setNotice('사건을 종료했고, 피드백과 블랙박스 역량 평가를 반영했습니다.');await load()}catch(e){setError(e instanceof Error?e.message:'진단 종료 실패')}finally{setBusy(false)}}
 const resume=(session:Session)=>{setActive(session);setNotes({facts:session.facts,hypotheses:session.hypotheses,unknowns:session.unknowns});setMessage('');setClosing(false);setConclusion('');setNotice('저장된 사건 세션을 이어서 엽니다.')}
 const dismiss=()=>{setActive(null);setClosing(false);setConclusion('')}
 return <div className="page blackbox-page">
  <section className="blackbox-hero"><div><p className="blackbox-eyebrow">BLACK-BOX DIAGNOSIS TRAINING</p><h1>역량 강화</h1><p>주소와 테스트 계정만 가진 상황에서 직접 관측하고 추리합니다. 코드, 로그, 첨부파일, 정답 후보는 제공하지 않습니다.</p></div><div className="blackbox-hero-metric"><small>현재 블랙박스 보완</small><strong>{weakest?labels[weakest.skillCode]??weakest.skillCode:'사건 분석 준비 중'}</strong><span>{weakest?`${weakest.blackBoxScore?.toFixed(0)}점 · 사건 ${weakest.blackBoxEvaluationCount}회`:'종료된 사건이 없습니다.'}</span></div></section>
  <nav className="blackbox-tabs"><button aria-pressed={tab==='overview'} onClick={()=>setTab('overview')}><Brain size={16}/>종합 역량</button><button aria-pressed={tab==='scenarios'} onClick={()=>setTab('scenarios')}><ShieldQuestion size={16}/>블랙박스 사건</button><button aria-pressed={tab==='history'} onClick={()=>setTab('history')}><History size={16}/>과거 기록</button></nav>
  {error&&<p className="blackbox-alert">{error}</p>}{notice&&<p className="blackbox-notice">{notice}</p>}
  {tab==='overview'&&<section className="blackbox-score-grid">{dashboard?.assessments.map(item=><article className="blackbox-score-card" key={item.skillCode}><span>{labels[item.skillCode]??item.skillCode}</span><div className="blackbox-score-pair"><div><small>기초 판단</small><strong>{item.score.toFixed(0)}</strong><em>기존 평가 {item.evaluationCount}회</em></div><div><small>블랙박스 추리</small><strong>{item.blackBoxScore===null?'—':item.blackBoxScore.toFixed(0)}</strong><em>{item.blackBoxEvaluationCount===0?'측정 전':`사건 ${item.blackBoxEvaluationCount}회`}</em></div></div><p>{item.blackBoxRationale??item.rationale}</p><small>{item.blackBoxNextAction??item.nextAction}</small></article>)}</section>}
  {tab==='scenarios'&&<section><p className="blackbox-rules">대화창에는 직접 수행하려는 테스트를 자연어로 적습니다. 안내는 해당 사건에서 외부 사용자가 관측할 수 있는 결과만 반환하며, 취약점 후보나 다음 행동을 제시하지 않습니다.</p><div className="blackbox-case-grid">{scenarios.map(s=><article className="blackbox-case" key={s.slug}><span className="blackbox-meta">{labels[s.skillCode]??s.skillCode} · 난이도 {s.difficulty}</span><h2>{s.title}</h2><p>{s.intro}</p><button className="blackbox-start" onClick={()=>void begin(s)} disabled={busy}>새 사건 시작</button></article>)}</div></section>}
  {tab==='history'&&<section className="blackbox-history-list">{history.length===0?<p className="blackbox-empty">아직 시작한 사건이 없습니다.</p>:history.map(s=><article className="blackbox-history-card" key={s.id}><div><small>{new Date(s.startedAt).toLocaleString('ko-KR')} · {s.status==='CLOSED'?'종료됨':'작성 중'}</small><h2>{s.title}</h2><p>{s.finalReport?.split('\n').find(line=>line.startsWith('판정:'))??'진단 진행 중'}</p></div><button className="blackbox-history-open" onClick={()=>s.status==='ACTIVE'?resume(s):setArchive(s)}>{s.status==='ACTIVE'?'이어 하기':'열람'}</button></article>)}</section>}
  {active&&<div className="blackbox-overlay" onMouseDown={dismiss}><aside className="blackbox-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header className="blackbox-modal-header"><div><p className="blackbox-eyebrow">BLACK-BOX CASE · {labels[active.skillCode]??active.skillCode}</p><h2>{active.title}</h2><p>{active.intro}</p></div><div className="blackbox-modal-actions">{active.status==='ACTIVE'&&<button className="blackbox-close" onClick={()=>setClosing(true)} disabled={busy}>진단 종료</button>}<button className="blackbox-icon-button" aria-label="닫기" onClick={dismiss} disabled={busy}><X/></button></div></header>{active.status==='ACTIVE'?<div className="blackbox-workspace"><section className="blackbox-chat"><div className="blackbox-chat-title"><MessageCircle size={16}/> 추리 대화</div><div className="blackbox-thread">{messages(active.messages).map((m,i)=><article className={`blackbox-message ${m.role==='USER'?'user':'coach'}`} key={`${i}-${m.text}`}><b>{m.role==='USER'?'나':'진단 안내'}</b><br/>{m.text}</article>)}</div><div className="blackbox-composer"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="직접 시도할 행동을 자유롭게 적으세요. 예: A 계정으로 주문 번호만 바꿔 조회한다." maxLength={1800}/><button className="blackbox-send" onClick={()=>void send()} disabled={busy||!message.trim()}><Send size={16}/>보내기</button></div></section><aside className="blackbox-notebook"><h3><ClipboardCheck size={17}/> 조사 메모</h3><p>사실, 가설, 미확인 사항을 직접 정리합니다. 저장 버튼을 눌러야 보존됩니다.</p>{([['facts','확인한 사실'],['hypotheses','가설'],['unknowns','아직 모르는 것']] as [keyof Notes,string][]).map(([key,label])=><label className="blackbox-note-field" key={key}><span>{label}</span><textarea value={notes[key]} onChange={e=>setNotes(now=>({...now,[key]:e.target.value}))} placeholder={`${label}을 적으세요.`} disabled={busy}/></label>)}<button className="blackbox-save" onClick={()=>void saveNotes()} disabled={busy}><Save size={15}/>메모 저장</button></aside></div>:<section className="blackbox-final"><article><h3>진단 결과</h3><ReactMarkdown>{active.finalReport??''}</ReactMarkdown></article><article><h3>피드백</h3><ReactMarkdown>{active.feedbackMd??''}</ReactMarkdown></article></section>}{closing&&<div className="blackbox-overlay" onMouseDown={()=>setClosing(false)}><section className="blackbox-close-panel" onMouseDown={e=>e.stopPropagation()}><h2>진단 종료</h2><p>종료 후 이 세션의 대화와 메모는 평가 근거로 고정됩니다. 재시도에는 이 기록이 자동으로 보이지 않습니다.</p><label>최종 판정<select value={verdict} onChange={e=>setVerdict(e.target.value)}><option>취약점 확인</option><option>추가 증거 필요</option><option>취약점 아님</option></select></label><label>진단 결론<textarea value={conclusion} onChange={e=>setConclusion(e.target.value)} placeholder="확정된 사실과 아직 확정하지 못한 범위를 짧게 작성하세요." maxLength={1800}/></label><div className="blackbox-close-actions"><button onClick={()=>setClosing(false)} disabled={busy}>계속 추리</button><button onClick={()=>void finish()} disabled={busy||!conclusion.trim()}>{busy?'종료 중…':'종료·평가 반영'}</button></div></section></div>}</aside></div>}
  {archive&&<div className="blackbox-overlay" onMouseDown={()=>setArchive(null)}><aside className="blackbox-close-panel" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="blackbox-icon-button" aria-label="닫기" onClick={()=>setArchive(null)}><X/></button><p className="blackbox-eyebrow">PAST SESSION · READ ONLY</p><h2>{archive.title}</h2><small>{new Date(archive.startedAt).toLocaleString('ko-KR')} · {archive.status==='CLOSED'?'종료됨':'작성 중'}</small>{archive.finalReport&&<ReactMarkdown>{archive.finalReport}</ReactMarkdown>}{archive.feedbackMd&&<ReactMarkdown>{archive.feedbackMd}</ReactMarkdown>}<h3>조사 메모</h3><p>{archive.facts||'기록 없음'}</p><p>{archive.hypotheses||'기록 없음'}</p><p>{archive.unknowns||'기록 없음'}</p></aside></div>}
 </div>
}
