export type OmakaseFile = { id: string; title: string; path: string }
export type OmakaseSection = { title: string; fileIds: string[] }
export type OmakaseTopic = {
  id: string
  title: string
  subtitle: string
  accent: string
  files: OmakaseFile[]
  sections: OmakaseSection[]
}

// 각 토픽은 /public/omakase-content/<id>/ 밑에 정적 마크다운 파일로 존재 — 런타임에 fetch() 로 읽어온다.
// (폴더명을 /omakase 로 두면 SPA 라우트 /omakase 와 겹쳐서 nginx가 디렉터리로 보고 301→403 내버린다.)
// 파일명은 ASCII 숫자(01.md..)로 고정해 인코딩/URL 이슈를 피하고, 실제 표시 제목은 여기 title 로 따로 관리.
export const OMAKASE_TOPICS: OmakaseTopic[] = [
  {
    id: 'pentest-server-to-cloud',
    title: '서버 한 대로 시작하는 실전 모의해킹',
    subtitle: '셸 접속부터 Apache·Tomcat·Oracle DB, AWS·CDN 공격 경로, 최종 보고서까지 — 22강',
    accent: '#58a6ff',
    sections: [
      { title: '섹션 1. 리눅스 서버 한 대 완전정복', fileIds: ['01', '02', '03', '04', '05', '06'] },
      { title: '섹션 2. 웹 서버와 애플리케이션', fileIds: ['07', '08'] },
      { title: '섹션 3. 데이터베이스와 전체 흐름', fileIds: ['09', '10'] },
      { title: '섹션 4. 공격 경로 조립과 증명', fileIds: ['11', '12', '13', '14', '15'] },
      { title: '섹션 5. 클라우드로 확장하기', fileIds: ['16', '17', '18', '19', '20'] },
      { title: '섹션 6. 독립 진단과 마무리', fileIds: ['21', '22'] },
    ],
    files: [
      { id: '01', title: '01. 서버 진입과 셸: 진단자의 사고방식 세우기', path: '/omakase-content/pentest-server-to-cloud/01.md' },
      { id: '02', title: '02. 파일과 경로 탐색: 서비스로부터 설정을 역추적하기', path: '/omakase-content/pentest-server-to-cloud/02.md' },
      { id: '03', title: '03. 계정과 파일 권한: effective 권한과 신뢰 매트릭스', path: '/omakase-content/pentest-server-to-cloud/03.md' },
      { id: '04', title: '04. 프로세스와 서비스: 실행 상태의 증거 잡기', path: '/omakase-content/pentest-server-to-cloud/04.md' },
      { id: '05', title: '05. 네트워크와 방화벽', path: '/omakase-content/pentest-server-to-cloud/05.md' },
      { id: '06', title: '06. 로그, 패키지와 SELinux', path: '/omakase-content/pentest-server-to-cloud/06.md' },
      { id: '07', title: '07. Apache 요청 경로: URL에서 실제 파일 또는 WAS까지 추적하기', path: '/omakase-content/pentest-server-to-cloud/07.md' },
      { id: '08', title: '08. Tomcat과 앱 배포: 공통 실습 앱 labapp의 구조 확정', path: '/omakase-content/pentest-server-to-cloud/08.md' },
      { id: '09', title: '09. Oracle DB 최소 조작', path: '/omakase-content/pentest-server-to-cloud/09.md' },
      { id: '10', title: '10. 전체 서비스 연결 진단', path: '/omakase-content/pentest-server-to-cloud/10.md' },
      { id: '11', title: '11. 자산과 신뢰 경계: 지금까지의 조각을 하나의 지도로 조립하기', path: '/omakase-content/pentest-server-to-cloud/11.md' },
      { id: '12', title: '12. 파일 읽기 영향 범위: 필터는 왜, 어떻게 뚫리는가', path: '/omakase-content/pentest-server-to-cloud/12.md' },
      { id: '13', title: '13. 노출 정보와 다음 단계', path: '/omakase-content/pentest-server-to-cloud/13.md' },
      { id: '14', title: '14. 접근 경로와 권한 검증', path: '/omakase-content/pentest-server-to-cloud/14.md' },
      { id: '15', title: '15. 영향 입증과 수정', path: '/omakase-content/pentest-server-to-cloud/15.md' },
      { id: '16', title: '16. AWS 최소망과 EC2: 클라우드 네트워크를 진단자의 눈으로 읽기', path: '/omakase-content/pentest-server-to-cloud/16.md' },
      { id: '17', title: '17. IAM 역할과 S3 권한: 메타데이터 탈취 패턴을 실무 깊이로 이해하기', path: '/omakase-content/pentest-server-to-cloud/17.md' },
      { id: '18', title: '18. AWS 공격 경로 검증: 리눅스 파일 노출을 클라우드 맥락으로 확장하기', path: '/omakase-content/pentest-server-to-cloud/18.md' },
      { id: '19', title: '19. CloudFront 오리진과 캐시: CDN이 숨기는 것과 드러내는 것', path: '/omakase-content/pentest-server-to-cloud/19.md' },
      { id: '20', title: '20. Cloudflare 진단 관점 비교: 같은 질문, 다른 화면', path: '/omakase-content/pentest-server-to-cloud/20.md' },
      { id: '21', title: '21. 독립 인프라 진단', path: '/omakase-content/pentest-server-to-cloud/21.md' },
      { id: '22', title: '22. 최종 보고와 재검증', path: '/omakase-content/pentest-server-to-cloud/22.md' },
    ],
  },
  {
    id: 'web-vuln-diagnosis-checklist',
    title: '현업 진단자의 웹 취약점 체크리스트',
    subtitle: 'XSS부터 접근제어 우회까지, 8대 영역 28개 진단 항목 한 번에 정리',
    accent: '#f78166',
    sections: [
      { title: '1장. 입력값 검증', fileIds: ['1-1', '1-2', '1-3', '1-4', '1-5', '1-6'] },
      { title: '2장. 파일 업로드·다운로드', fileIds: ['2-1', '2-2'] },
      { title: '3장. 인증과 계정 관리', fileIds: ['3-1', '3-2', '3-3', '3-4', '3-5', '3-6'] },
      { title: '4장. 세션과 접근제어', fileIds: ['4-1', '4-2', '4-3', '4-4', '4-5'] },
      { title: '5장. 정보 노출 (소스·통신)', fileIds: ['5-1', '5-2'] },
      { title: '6장. 오류 처리', fileIds: ['6-1', '6-2'] },
      { title: '7장. 서버 설정', fileIds: ['7-1', '7-2', '7-3', '7-4'] },
      { title: '8장. 기타', fileIds: ['8-1'] },
    ],
    files: [
      { id: '1-1', title: '1-1. XSS / CSRF 공격 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/1-1.md' },
      { id: '1-2', title: '1-2. 삽입(Injection) 공격 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/1-2.md' },
      { id: '1-3', title: '1-3. 파라미터 값 및 히든(Hidden) 필드 조작 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/1-3.md' },
      { id: '1-4', title: '1-4. SSRF / File Inclusion 공격 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/1-4.md' },
      { id: '1-5', title: '1-5. 검증되지 않은 리다이렉트와 포워드', path: '/omakase-content/web-vuln-diagnosis-checklist/1-5.md' },
      { id: '1-6', title: '1-6. 입력 값 크기 및 무결성 검증 오류', path: '/omakase-content/web-vuln-diagnosis-checklist/1-6.md' },
      { id: '2-1', title: '2-1. 악성코드파일 업로드', path: '/omakase-content/web-vuln-diagnosis-checklist/2-1.md' },
      { id: '2-2', title: '2-2. 중요 정보 파일 다운로드 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/2-2.md' },
      { id: '3-1', title: '3-1. 패스워드 정책 유무 및 반영 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/3-1.md' },
      { id: '3-2', title: '3-2. 인증 실패 횟수 제한', path: '/omakase-content/web-vuln-diagnosis-checklist/3-2.md' },
      { id: '3-3', title: '3-3. 계정 정보 파악 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/3-3.md' },
      { id: '3-4', title: '3-4. 관리자 페이지 분리 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/3-4.md' },
      { id: '3-5', title: '3-5. 검색엔진 정보 노출 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/3-5.md' },
      { id: '3-6', title: '3-6. 백업 파일 및 테스트 파일 존재 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/3-6.md' },
      { id: '4-1', title: '4-1. 쿠키(Cookie) 및 웹 스토리지(Web Storage) 조작 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/4-1.md' },
      { id: '4-2', title: '4-2. 인증(세션 및 토큰) 값 안전성 설정 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/4-2.md' },
      { id: '4-3', title: '4-3. 접근제어 우회 가능성 확인', path: '/omakase-content/web-vuln-diagnosis-checklist/4-3.md' },
      { id: '4-4', title: '4-4. 비인증 상태로 중요 page 접근 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/4-4.md' },
      { id: '4-5', title: '4-5. 일반계정 권한 상승 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/4-5.md' },
      { id: '5-1', title: '5-1. 소스코드 내 주요정보 노출 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/5-1.md' },
      { id: '5-2', title: '5-2. 요청 및 응답 값 내 주요정보 포함여부 확인', path: '/omakase-content/web-vuln-diagnosis-checklist/5-2.md' },
      { id: '6-1', title: '6-1. 오류페이지를 통한 정보 노출 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/6-1.md' },
      { id: '6-2', title: '6-2. 일괄적인 오류 처리 페이지 존재 여부', path: '/omakase-content/web-vuln-diagnosis-checklist/6-2.md' },
      { id: '7-1', title: '7-1. Client Request Method', path: '/omakase-content/web-vuln-diagnosis-checklist/7-1.md' },
      { id: '7-2', title: '7-2. 파일 목록화 가능성', path: '/omakase-content/web-vuln-diagnosis-checklist/7-2.md' },
      { id: '7-3', title: '7-3. 서버 헤더정보 노출', path: '/omakase-content/web-vuln-diagnosis-checklist/7-3.md' },
      { id: '7-4', title: '7-4. 취약한 보안설정', path: '/omakase-content/web-vuln-diagnosis-checklist/7-4.md' },
      { id: '8-1', title: '8-1. 취약점 진단 항목에 정의되지 않은 취약점', path: '/omakase-content/web-vuln-diagnosis-checklist/8-1.md' },
    ],
  },
  {
    id: 'kisa-critical-infra-standard',
    title: '국가 기반시설 진단관의 취약점 분석·평가 표준',
    subtitle: 'Unix·Windows부터 제어시스템·클라우드까지, 한국인터넷진흥원 가이드 9대 영역 18장 완전판',
    accent: '#3fb950',
    sections: [
      { title: '1장. Unix/Linux 서버', fileIds: ['1-1', '1-2', '1-3', '1-4'] },
      { title: '2장. Windows 서버', fileIds: ['2-1', '2-2', '2-3'] },
      { title: '3장. 웹 서버(WAS) 설정', fileIds: ['3-1'] },
      { title: '4장. 보안장비 운영', fileIds: ['4-1'] },
      { title: '5장. 네트워크 장비', fileIds: ['5-1', '5-2'] },
      { title: '6장. 제어시스템(OT/ICS)', fileIds: ['6-1', '6-2'] },
      { title: '7장. DBMS', fileIds: ['7-1', '7-2'] },
      { title: '8장. 웹 애플리케이션 보안', fileIds: ['8-1', '8-2'] },
      { title: '9장. 가상화·클라우드', fileIds: ['9-1'] },
    ],
    files: [
      { id: '1-1', title: '1-1. Unix 서버 계정 관리와 인증 정책', path: '/omakase-content/kisa-critical-infra-standard/1-1.md' },
      { id: '1-2', title: '1-2. Unix 서버 파일 권한과 접근 통제', path: '/omakase-content/kisa-critical-infra-standard/1-2.md' },
      { id: '1-3', title: '1-3. Unix 네트워크 서비스 관리 — 메일·DNS·NFS·Telnet', path: '/omakase-content/kisa-critical-infra-standard/1-3.md' },
      { id: '1-4', title: '1-4. Unix FTP·SNMP 설정과 패치·로그 관리', path: '/omakase-content/kisa-critical-infra-standard/1-4.md' },
      { id: '2-1', title: '2-1. Windows 서버 계정·서비스 관리', path: '/omakase-content/kisa-critical-infra-standard/2-1.md' },
      { id: '2-2', title: '2-2. Windows 서비스 보안 설정 — FTP·DNS·원격 접속', path: '/omakase-content/kisa-critical-infra-standard/2-2.md' },
      { id: '2-3', title: '2-3. Windows 레지스트리·보안 정책 강화', path: '/omakase-content/kisa-critical-infra-standard/2-3.md' },
      { id: '3-1', title: '3-1. 웹 서버(WAS) 설정 보안', path: '/omakase-content/kisa-critical-infra-standard/3-1.md' },
      { id: '4-1', title: '4-1. 보안장비(방화벽·IDS) 운영 관리', path: '/omakase-content/kisa-critical-infra-standard/4-1.md' },
      { id: '5-1', title: '5-1. 네트워크 장비 계정·패치·로깅 관리', path: '/omakase-content/kisa-critical-infra-standard/5-1.md' },
      { id: '5-2', title: '5-2. 네트워크 장비 불필요 서비스 차단', path: '/omakase-content/kisa-critical-infra-standard/5-2.md' },
      { id: '6-1', title: '6-1. 제어시스템(OT/ICS) 서비스·패치·네트워크 통제', path: '/omakase-content/kisa-critical-infra-standard/6-1.md' },
      { id: '6-2', title: '6-2. 제어시스템 운영 보안과 Windows 기반 HMI 보호', path: '/omakase-content/kisa-critical-infra-standard/6-2.md' },
      { id: '7-1', title: '7-1. DBMS 계정 관리와 접근 통제', path: '/omakase-content/kisa-critical-infra-standard/7-1.md' },
      { id: '7-2', title: '7-2. DBMS 옵션·패치 관리와 리스너 보안', path: '/omakase-content/kisa-critical-infra-standard/7-2.md' },
      { id: '8-1', title: '8-1. 웹 애플리케이션 핵심 취약점 — XSS·CSRF·SSRF·세션·JWT', path: '/omakase-content/kisa-critical-infra-standard/8-1.md' },
      { id: '8-2', title: '8-2. 웹 애플리케이션 부가 점검과 가상화 전환부', path: '/omakase-content/kisa-critical-infra-standard/8-2.md' },
      { id: '9-1', title: '9-1. 가상화·클라우드 환경 보안', path: '/omakase-content/kisa-critical-infra-standard/9-1.md' },
    ],
  },
]
