import { useEffect, useState, type FormEvent } from 'react'
import { Plus, Trash2, X } from 'lucide-react'
import type { ResearchSource, SourceCandidateEntry, Task } from '../lib/types'
import { PanelShell } from '../components/shared'

export function SourceRegistry({ onClose, onTaskStarted, readOnly, embedded }: { onClose?: () => void; onTaskStarted: (task: Task) => void; readOnly?: boolean; embedded?: boolean }) {
  const [sources, setSources] = useState<ResearchSource[]>([]); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [domain, setDomain] = useState<'SECURITY' | 'ECONOMY'>('SECURITY'); const [intervalHours, setIntervalHours] = useState(24); const [crawlDepth, setCrawlDepth] = useState(1); const [maxPages, setMaxPages] = useState(20); const [note, setNote] = useState(''); const [editingId, setEditingId] = useState<string | null>(null); const [collectingId, setCollectingId] = useState<string | null>(null); const [notice, setNotice] = useState('')
  const [candidates, setCandidates] = useState<SourceCandidateEntry[]>([]); const [decidingId, setDecidingId] = useState<string | null>(null); const [discovering, setDiscovering] = useState<'SECURITY' | 'ECONOMY' | null>(null)
  const load = () => fetch('/api/research-sources', { credentials: 'include' }).then(r => r.ok ? r.json() : []).then(setSources).catch(() => setNotice('등록 목록을 불러오지 못했습니다.'))
  const loadCandidates = () => fetch('/api/source-candidates', { credentials: 'include' }).then(r => r.ok ? r.json() : []).then(setCandidates).catch(() => undefined)
  useEffect(() => { load(); if (!readOnly) loadCandidates() }, [])
  const decide = async (candidate: SourceCandidateEntry, action: 'approve' | 'reject') => { setDecidingId(candidate.id); await fetch(`/api/source-candidates/${candidate.id}/${action}`, { method: 'POST', credentials: 'include' }); setDecidingId(null); loadCandidates(); if (action === 'approve') load() }
  const discoverNow = async (target: 'SECURITY' | 'ECONOMY') => { setDiscovering(target); setNotice(''); const response = await fetch(`/api/source-candidates/discover-now?domain=${target}`, { method: 'POST', credentials: 'include' }); const result = response.ok ? await response.json() as { proposed: number } : null; setDiscovering(null); setNotice(result ? `${target === 'SECURITY' ? '보안' : '경제'} 분야에서 ${result.proposed}개 후보를 새로 찾았습니다.` : '후보 탐색에 실패했습니다.'); loadCandidates() }
  const reset = () => { setName(''); setUrl(''); setIntervalHours(24); setCrawlDepth(1); setMaxPages(20); setNote(''); setEditingId(null) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setNotice(''); const response = await fetch(editingId ? `/api/research-sources/${editingId}` : '/api/research-sources', { method: editingId ? 'PUT' : 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, domain, intervalHours, crawlDepth, maxPages, note, ...(editingId ? {} : { url }) }) }); if (!response.ok) { setNotice('이름과 http(s) 링크를 확인해 주세요.'); return } reset(); load() }
  const collectNow = async (source: ResearchSource) => { setCollectingId(source.id); setNotice(`${source.name} 수집을 시작했습니다…`); const response = await fetch(`/api/research-sources/${source.id}/collect-now`, { method: 'POST', credentials: 'include' }); const result = response.ok ? await response.json() : null; setCollectingId(null); if (!result) { setNotice('즉시 수집에 실패했습니다. URL 또는 접근 제한을 확인해 주세요.'); return } setNotice(result.changedPages > 0 ? `${source.name}: ${result.savedPages}개 저장, ${result.failedPages}개 실패 · 변경된 ${result.changedPages}개 페이지를 분석 에이전트에 전달했습니다.` : `${source.name}: ${result.savedPages}개 저장, ${result.failedPages}개 실패 · 이전과 내용이 동일해 분석을 건너뛰었습니다.`); load(); if (result.analysisTaskId) { const taskResponse = await fetch(`/api/tasks/${result.analysisTaskId}`, { credentials: 'include' }); if (taskResponse.ok) onTaskStarted(await taskResponse.json() as Task) } }
  return <PanelShell embedded={embedded} className="source-sheet"><div className="sheet-header"><div><p className="eyebrow">SOURCE REGISTRY</p><h2>수집 사이트</h2></div>{onClose && <button className="sheet-close" onClick={onClose}><X size={18}/></button>}</div><p className="source-intro">공개 사이트를 등록하면 같은 도메인에서 지정 깊이만큼 링크를 따라 수집합니다. <b>즉시 수집</b>은 저장 결과를 바로 알려드립니다.</p>
    {!readOnly && <div className="candidate-section"><div className="source-list-head"><b>AI 추천 출처 후보</b><span>{candidates.length}건 대기</span></div><p className="source-intro small">등록된 출처와 비슷한 수준의 새 출처를 주기적으로 찾아 제안합니다. 바로 등록되지 않고, 승인해야만 실제 수집 대상이 됩니다.</p>
      <div className="discover-actions"><button type="button" onClick={() => discoverNow('SECURITY')} disabled={discovering !== null}>{discovering === 'SECURITY' ? '탐색 중…' : '보안 후보 지금 찾기'}</button><button type="button" onClick={() => discoverNow('ECONOMY')} disabled={discovering !== null}>{discovering === 'ECONOMY' ? '탐색 중…' : '경제 후보 지금 찾기'}</button></div>
      {candidates.length > 0 && <div className="candidate-list">{candidates.map(candidate => <article className="candidate-row" key={candidate.id}><span className={`domain-dot ${candidate.domain.toLowerCase()}`}/><div><b>{candidate.name}</b><a href={candidate.url} target="_blank" rel="noreferrer">{candidate.url}</a><small>{candidate.justification}</small><div className="source-actions"><button onClick={() => decide(candidate, 'approve')} disabled={decidingId === candidate.id}>승인</button><button onClick={() => decide(candidate, 'reject')} disabled={decidingId === candidate.id}>거절</button></div></div></article>)}</div>}
    </div>}
    {!readOnly && <form className="source-form" onSubmit={submit}><label>표시 이름<input value={name} onChange={e => setName(e.target.value)} required maxLength={120}/></label><label>링크<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://example.com" required type="url" disabled={Boolean(editingId)}/></label><label>담당 팀<select value={domain} onChange={e => setDomain(e.target.value as 'SECURITY' | 'ECONOMY')}><option value="SECURITY">보안</option><option value="ECONOMY">경제</option></select></label><label>수집 주기(시간)<input value={intervalHours} onChange={e => setIntervalHours(Number(e.target.value))} type="number" min="1" max="168" required/></label><label>링크 탐색 깊이<select value={crawlDepth} onChange={e => setCrawlDepth(Number(e.target.value))}><option value={0}>0단계 · 등록 주소만</option><option value={1}>1단계 · 링크 한 번</option><option value={2}>2단계 · 링크 두 번</option></select></label><label>최대 페이지<input value={maxPages} onChange={e => setMaxPages(Number(e.target.value))} type="number" min="1" max="100" required/></label><label>설명(선택)<textarea value={note} onChange={e => setNote(e.target.value)} maxLength={4000} rows={2} placeholder="이 출처를 등록한 이유나 특징을 적어두면 나중에 알아보기 쉽습니다."/></label>{notice && <p className={notice.includes('실패') ? 'form-error' : 'form-notice'}>{notice}</p>}<button className="source-add" type="submit"><Plus size={16}/>{editingId ? '설정 저장' : '사이트 등록'}</button>{editingId && <button className="source-cancel" type="button" onClick={reset}>편집 취소</button>}</form>}
    <div className="source-list"><div className="source-list-head"><b>등록됨</b><span>{sources.length}개</span></div>{sources.map(source => <article className="source-row" key={source.id}><span className={`domain-dot ${source.domain.toLowerCase()}`}/><div><b>{source.name}</b>{source.consecutiveNoContentCycles >= 3 && <span className="source-no-content-badge" title={`최근 ${source.consecutiveNoContentCycles}회 연속 수집에서 새 내용이 없었습니다.`}>비활성화 고려 · {source.consecutiveNoContentCycles}회 연속 무의미</span>}<a href={source.url} target="_blank" rel="noreferrer">{source.url}</a><small>{source.domain === 'SECURITY' ? '보안 팀' : '경제 팀'} · {source.intervalHours}시간 · 깊이 {source.crawlDepth} · 최대 {source.maxPages}페이지</small>{source.note && <small className="source-note">{source.note}</small>}{!readOnly && <div className="source-actions"><button onClick={() => collectNow(source)} disabled={collectingId === source.id}>{collectingId === source.id ? '수집 중…' : '즉시 수집'}</button><button onClick={() => { setEditingId(source.id); setName(source.name); setUrl(source.url); setDomain(source.domain); setIntervalHours(source.intervalHours); setCrawlDepth(source.crawlDepth); setMaxPages(source.maxPages); setNote(source.note ?? ''); setNotice('') }}>설정</button></div>}</div>{!readOnly && <button onClick={() => fetch(`/api/research-sources/${source.id}`, { method: 'DELETE', credentials: 'include' }).then(load)}><Trash2 size={15}/></button>}</article>)}</div></PanelShell>
}
